/**
 * Writes src/version.ts from the version in package.json.
 *
 * Parcel has no equivalent of rollup's `output.intro`, and importing
 * package.json directly would inline the whole file into the bundle. Running
 * this before every build keeps the number the card reports the released one
 * instead of something somebody has to remember to bump.
 */
import { readFileSync, writeFileSync } from "node:fs";

const { version } = JSON.parse(readFileSync("package.json", "utf8"));

writeFileSync(
  "src/version.ts",
  `// Generated by scripts/gen-version.mjs — do not edit; bump the version in\n` +
    `// package.json instead.\nexport const CARD_VERSION = ${JSON.stringify(version)};\n`,
);
